---
id:
  label: ID
  position: '1'
  type: label
  visible: '1'
  options:
    disabled : '0'
    readonly: '1'
name:
  label: Name
  position: '3'
  type: text
  visible: '1'
  options:
    disabled : '0'
    readonly: '1'
surname:
  label: Surname
  position: '2'
  type: text
  visible: '1'
  options:
    disabled : '0'
    readonly: '1'
user_hash:
  label: Hash
  position: '4'
  type: text
  visible: '1'
  options:
    disabled : '0'
    readonly: '1'
